# Generated by Django 5.1.1 on 2024-09-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240928_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
